### ISSUE TITLE
Proposal for an additional link

### ISSUE THREAD

**Issue by thomacos** [aarnaud/k8s-directx-device-plugin#1]
[https://techcommunity.microsoft.com/t5/Containers/Bringing-GPU-acceleration-to-Windows-containers/ba-p/393939](https://techcommunity.microsoft.com/t5/Containers/Bringing-GPU-acceleration-to-Windows-containers/ba-p/393939)

**Comment by aarnaud** [comment]
Ok, can you do a PR ?

**Comment by thomacos** [comment]
See https://github.com/aarnaud/k8s-directx-device-plugin/pull/3.
