### ISSUE TITLE
kublet fail to start with bind error

### ISSUE THREAD

**Issue by TrueGreens** [aarnaud/k8s-directx-device-plugin#4]
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0403 09:45:41.307993    4252 kubelet.go:1377] Failed to start ContainerManager listen unix c:\var\lib\kubelet\device-plugins\kubelet.sock: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

Attaching error logs:
[kubelet.exe.ERROR.txt](https://github.com/aarnaud/k8s-directx-device-plugin/files/4440541/kubelet.exe.ERROR.txt)

**Comment by aarnaud** [comment]
Maybe related to some specific windows version or a kubelet bug:
https://github.com/kubernetes/kubernetes/pull/80917#issuecomment-528361351

**Comment by aarnaud** [comment]
Also depends of your windows version you have to edit `c:\k\start-kubelet.ps1`

```
...
ipmo $helper
 
#Add this line below
Remove-Item c:\var\lib\kubelet\device-plugins\kubelet.sock -ErrorAction Ignore
 
if ($RegisterOnly.IsPresent)
{
    RegisterNode
    exit
}
...
```
There is a lite issue for Linux Socket on Windows `c:\var\lib\kubelet\device-plugins\kubelet.sock` 

Tested on windows server 2019 with docker 19.03

**Comment by TrueGreens** [comment]
Just curious why that line is needed.  Everytime I started the script, the folder for the kubelet.sock is always empty.
It now works.  I'm also using windows server 2019 (1809) with docker 19.03.4 and k8s 1.16.2

Thank you :)
