### ISSUE TITLE
Using DirectX without plugin

### ISSUE THREAD

**Issue by clementrey** [aarnaud/k8s-directx-device-plugin#5]
Hello
Is there a way to use you development without plugin (I cannot change the kubelet) ? 

Best Regards

**Comment by aarnaud** [comment]
Hello @clementrey 
unfortunately, I'm alone to push device-manager in kubelet for windows. My PR #80917 was made in August 2019. I will try next week to rebase and update this PR for the next Kubernetes release.

https://github.com/kubernetes/kubernetes/pull/80917

**Comment by clementrey** [comment]
Thank you,
Do you think a solution based on VolumeDevices or VolumeMount could be implemented ?

Best Regards
Clement

**Comment by aarnaud** [comment]
I don't think, because Volume Devices/Mount has input validation that don't work with directx class id

**Comment by clementrey** [comment]
Ok thank you reply.
I managed to find a way to update my kubelet with the relased in this repo but I got an error : 
The k8s pause container cannot be created: (logs from the docker engine running on the windows host) 
'''
'\"PAUSE <CON\"' is not recognized as an internal or external command,
operable program or batch file.
'''

Do you know the reason of that  ?
Best Regards

**Comment by aarnaud** [comment]
on windows server 2019 (1809 or higher) ?

**Comment by clementrey** [comment]
Hi,

I Investigated and I found out that my issue is related with an update of the docker engine. My cluster has been set up for docker 18.xx and the issue happened right after the update to 19.03.
It is not related to your kubelet.

Sorry for bothering
Clement

**Comment by clementrey** [comment]
Hi,

I Investigated and I found out that my issue is related with an update of the docker engine. My cluster has been set up for docker 18.xx and the issue happened right after the update to 19.03.
It is not related to your kubelet.

Sorry for bothering
Clement
